### PR TITLE
New logo for vroom

### PR DESCRIPTION
**Pull request by groschovskiy**

### CODE REVIEW

**Comment by groschovskiy** [comment]
@dbarnett could you please review new logo changes? Thanks in advance!

**Comment by dbarnett** [comment]
I like it!

Why is the "R" capitalized, though?

**Comment by groschovskiy** [comment]
Capital "R" looks better :)

**Comment by dbarnett** [comment]
K, it looks alright capitalized but made me wonder if there's some pun on the word "Room" that I'm missing.

**Pull request merged**
