### PR TITLE
The new logo of the project

### LINKED ISSUE #82: Vroom needs a logo / icon
Would be cool if we had a logo to include in the docs and the deb.

I'm assuming this would be some kind of a "V" with speed axes or tires spinning or something else speed-related, but could be something more creative if anyone has ideas.

### PR DESCRIPTION
**Pull request by groschovskiy**
Partially fixes #82.

### CODE REVIEW

**Comment by dbarnett** [comment]
Just curious, is that a moon or something else? Since it's a testing product, we may want to incorporate green instead of red. =)

**Comment by groschovskiy** [comment]
David I update logo (Green Version), review and make pull request

**Comment by dbarnett** [comment]
Probably want to put this in an `images/` subdir (or "resources" or something?). Other than that, LGTM.

**Comment by dbarnett** [comment]
Once we get a small app icon to go with it we can mark #82 fixed.

BTW, haven't heard any opinions from anyone else, but we can at least take it as a v1 and discuss whether to make any further changes once more people have seen it.

**Comment by groschovskiy** [comment]
This is beta version icon v0.1, icon for release I make beautyful

**Comment by groschovskiy** [comment]
@dbarnett hello. I updated now logo for vroom. This is for first time, later I re-design new version.

**Comment by dbarnett** [comment]
Can you move it into an images/ subdir?

Still kind of prefer the slanting letters and something a little closer to my sketch, but I guess this is fine for now.

**Comment by groschovskiy** [comment]
@dbarnett complete :+1:

**Comment by dbarnett** [comment]
LGTM.

**Pull request merged**
